- name: Replace string
uses: frabert/replace-string-action@v2.0
with:
  pattern: ''
  string: 'amerox'
  replace-with: 'amerox'
  
  - name: Replace string
uses: frabert/replace-string-action@v2.0
with:
  pattern: ''
  string: 'amero'
  replace-with: 'amero'

  - name: Replace string
uses: frabert/replace-string-action@v2.0
with:
  pattern: ''
  string: 'Amero'
  replace-with: 'Amero'
